### ISSUE TITLE
早期作品不能使用，希望增加功能

### ISSUE THREAD

**Issue by 2fdvr** [LunarConcerto/AutoRenameToolForDoujinOnsei#2]
很多早期作品报错不能正常重命名(例：RJ187922)，
目测是网站上没有声优字段，这种情况能否跳过字段而不是放弃重命名

另外希望贩卖日提供六位纯数字格式，和能够以单空格修饰字段,
期望效果：
> [DLsite] [190113] メイドと暮らそ♪くるみちゃんと一緒【バイノーラル】 RJ243414 (阿澄佳奈)

**Comment by LunarConcerto** [comment]
你好，如果你还需要使用本程序的话，请移步 <a href="https://github.com/LunarConcerto/MRT">MRT</a> ，这是我重制的版本，对你描述的问题已经进行修改 。

本程序将不再维护。
